### ISSUE TITLE
Scripts provided don't work

### ISSUE THREAD

**Issue by Ricocotam** [microsoft/MSMARCO-Conversational-Search#1]
Hi, I tried to use the provided scripts to download and generate data but the README doesn't match de python files.

README :
```
python generateQuerySets.py <msmarco train queries> <msmarco dev queries> <msmarco eval queries> <quoraQueries> <NQFolder>
```

Python File :
```
python generateQuerysets.py <msmarco train queries> <msmarco dev queries> <msmarco eval queries> <quoraQueries> <NQFolder> <unused msmarco> <sessions>
```

I supposed I had to use the "generateArtificialSessions.py" file but I need embeddings which are only available once the first file has been executed. It seems there's a circular need.

**Comment by spacemanidol** [comment]
We released the code more so people could see how we generated the sessions. For privacy reasons we will not be able to release the essions data and the unused sessions. GenerateQuerySets.py just concats together all the query sets mentioned to have a larger semantic space to map the real user sessions.

**Comment by Ricocotam** [comment]
Alright thanks, it wasn't clear
