### ISSUE TITLE
No root downloader

### ISSUE THREAD

**Issue by Ricocotam** [microsoft/MSMARCO-Conversational-Search#2]
Hi, is it feasible to have a downloadable file without sudo permissions ?

**Comment by spacemanidol** [comment]
Which files are you looking at? I havent had that problem with any files. Can't repro.

**Comment by Ricocotam** [comment]
I was talking about the `downloadData.sh` [file](https://github.com/microsoft/MSMARCO-Conversational-Search/blob/master/downloadData.sh). But as you said in #1 it's not supposed to be used like this
